
@startuml beanshell_7.3_DS.png
    skinparam handwritten false
    skinparam monochrome false
    skinparam packageStyle rect
    skinparam defaultFontName FG Virgil
    skinparam shadowing false
actor user
participant UIExtension 
participant MacrosPanel
participant ScriptUI




user -> ScriptUI : write ScriptController
user -> ScriptUI : execute
activate ScriptUI
create ScriptController
ScriptUI -> ScriptController : create()
ScriptUI -> ScriptController : run(String, workbook, spreadsheet, cell, macro)
deactivate ScriptUI
activate ScriptController
create BeanShellInterpreter
ScriptController -> BeanShellInterpreter : run(String, workbook, spreadsheet, cell, macro):Value
deactivate ScriptController
activate BeanShellInterpreter


participant UIController
BeanShellInterpreter -> UIController : getApp()
participant CleanSheets
BeanShellInterpreter -> CleanSheets : create()


create Macro
BeanShellInterpreter -> Macro : create(name:String, sp:SpreadSheet)
loop for each line
    BeanShellInterpreter -> Macro : addLine(lines:String)
end loop


BeanShellInterpreter -> Macro : evaluate()

deactivate BeanShellInterpreter
ScriptUI --> user : showValue()
deactivate ScriptUI

@enduml