@startuml
  box "Share Cell Auto Extension TCP cell sender"
    participant "ShareCellAutoExtension"
    participant "ShareCellAutoController"
    participant "ExtensionConnectionManager"
    participant "ObjectConnectionTCP"
    participant "SenderTCP"
    participant "Socket"
    participant "DataOutputStream"
  end box

create ShareCellAutoController 
    ShareCellAutoExtension -> ShareCellAutoController : create()
    ShareCellAutoExtension -> ShareCellAutoController : shareSelectedCells()
create ExtensionConnectionManager 
    ShareCellAutoController -> ExtensionConnectionManager : create()
    ShareCellAutoController -> ExtensionConnectionManager : cellMatrix = getSelectedCells()
create ObjectConnectionTCP 
    ExtensionConnectionManager -> ObjectConnectionTCP : new(tcpPort)
    ExtensionConnectionManager -> ObjectConnectionTCP : serverSendMessage(message, addressToSend)
create SenderTCP
    ObjectConnectionTCP -> SenderTCP : new(message, addressToSend)
create Socket
    SenderTCP -> Socket : socket = new Socket(ipAddress , tcpPort); 
    ObjectConnectionTCP -> SenderTCP : send()
   

create DataOutputStream
    SenderTCP -> DataOutputStream : new DataOutputStream(socket) 
    SenderTCP -> SenderTCP : send()
    note left of SenderTCP : it sends the object to another\n instance in the network
    note right of SenderTCP : it refreshes the information sent from time to time(parameter)
@enduml
