/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr4.blue.s1.core.n1150595.emailAndPhoneEdition.ui;

import eapli.framework.persistence.DataConcurrencyException;
import eapli.framework.persistence.DataIntegrityViolationException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import lapr4.blue.s1.core.n1150595.emailAndPhoneEdition.domain.email.Email;
import lapr4.blue.s1.core.n1150595.emailAndPhoneEdition.domain.phoneNumbers.countryCode.CountryCode;
import lapr4.white.s1.core.n4567890.contacts.application.ContactController;
import lapr4.white.s1.core.n4567890.contacts.domain.Contact;

/**
 *
 * @author 1150595
 */
public class EmailAndPhoneEditionUI extends javax.swing.JFrame {

    Contact cepe;
    ContactController ctrl;

    /**
     * Creates new form EmailAndPhoneEditionUI
     *
     * @param ctrl
     * @param cepe
     * @throws eapli.framework.persistence.DataIntegrityViolationException
     * @throws eapli.framework.persistence.DataConcurrencyException
     */
    public EmailAndPhoneEditionUI(/*UIController uiCtrl*/ContactController ctrl, Contact cepe) throws DataIntegrityViolationException, DataConcurrencyException {
        this.cepe = cepe;
        this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCelular2 = new javax.swing.JTextField();
        jLabelEmails = new javax.swing.JLabel();
        jLabelMain = new javax.swing.JLabel();
        jTextFieldMainEmail = new javax.swing.JTextField();
        jLabelHeader = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelWorkPhone = new javax.swing.JLabel();
        jLabelHomePhone = new javax.swing.JLabel();
        jLabelCelular1 = new javax.swing.JLabel();
        jLabelCelular2 = new javax.swing.JLabel();
        jTextFieldWorkPhone = new javax.swing.JTextField();
        jTextFieldHomePhone = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldCelular1 = new javax.swing.JTextField();
        jButtonAddSecondary = new javax.swing.JButton();
        jComboBoxSecondary = new javax.swing.JComboBox<>();
        jButtonSelectSecondary = new javax.swing.JButton();
        jLabelSelectedSecondary = new javax.swing.JLabel();
        jTextFieldSelectedSecondary = new javax.swing.JTextField();
        jButtonConfirmSecondary = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAddSecondary = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        String s="";
        if(this.cepe!=null){
            if(this.cepe.celular2()!=null){
                s=this.cepe.celular2().phoneNumber();
            }
        }
        jTextFieldCelular2.setText(s);

        jLabelEmails.setText("EMAILS");

        jLabelMain.setText("Main Email:");

        s="";
        if(this.cepe!=null){
            if(this.cepe.mainEmail()!=null){
                s=this.cepe.mainEmail().email();
            }
        }
        jTextFieldMainEmail.setText(s);

        jLabelHeader.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelHeader.setText("Email and Phone Edition");

        jLabelPhone.setText("PHONE NUMBERS");

        jLabelWorkPhone.setText("Work:");

        jLabelHomePhone.setText("Home:");

        jLabelCelular1.setText("Celular 1:");

        jLabelCelular2.setText("Celular 2:");

        s="";
        if(this.cepe!=null){
            if(this.cepe.workPhone()!=null){
                s=this.cepe.workPhone().phoneNumber();
            }
        }
        jTextFieldWorkPhone.setText(s);
        jTextFieldWorkPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWorkPhoneActionPerformed(evt);
            }
        });

        s="";
        if(this.cepe!=null){
            if(this.cepe.homePhone()!=null){
                s=this.cepe.homePhone().phoneNumber();
            }
        }
        jTextFieldHomePhone.setText(s);
        jTextFieldHomePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHomePhoneActionPerformed(evt);
            }
        });

        jButtonOk.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        s="";
        if(this.cepe!=null){
            if(this.cepe.celular1()!=null){
                s=this.cepe.celular1().phoneNumber();
            }
        }
        jTextFieldCelular1.setText(s);

        jButtonAddSecondary.setText("Add");
        jButtonAddSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSecondaryActionPerformed(evt);
            }
        });

        DefaultComboBoxModel model = new DefaultComboBoxModel<>();
        if(this.cepe!=null){
            if(this.cepe.secondaryEmails()!=null){
                model=lapr4.blue.s1.core.n1150595.emailAndPhoneEdition.Utils.
                comboBoxModelEmails(this.cepe.secondaryEmails());
            }
        }
        jComboBoxSecondary.setModel(model);
        jComboBoxSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSecondaryActionPerformed(evt);
            }
        });

        jButtonSelectSecondary.setText("Select");
        jButtonSelectSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectSecondaryActionPerformed(evt);
            }
        });

        jLabelSelectedSecondary.setText("Selected Secondary Email:");

        jTextFieldSelectedSecondary.setToolTipText("To remove this secondary email leave the field empty and press \"Confirm\".");
        jTextFieldSelectedSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSelectedSecondaryActionPerformed(evt);
            }
        });

        jButtonConfirmSecondary.setText("Confirm");
        jButtonConfirmSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmSecondaryActionPerformed(evt);
            }
        });

        jLabel1.setText("Existing Secondary Emails:");

        jLabel2.setText("New Secondary Email:");

        jTextFieldAddSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddSecondaryActionPerformed(evt);
            }
        });

        jLabel3.setText("Secondary Emails");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButtonCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPhone)
                            .addComponent(jLabelWorkPhone)
                            .addComponent(jLabelHomePhone)
                            .addComponent(jLabelCelular1)
                            .addComponent(jLabelCelular2)
                            .addComponent(jLabelEmails)
                            .addComponent(jLabelMain)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabelHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelSelectedSecondary)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldAddSecondary, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                .addComponent(jComboBoxSecondary, 0, 416, Short.MAX_VALUE)
                                .addComponent(jTextFieldCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldWorkPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMainEmail))
                            .addComponent(jTextFieldSelectedSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConfirmSecondary)
                            .addComponent(jButtonSelectSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelHeader)
                .addGap(18, 18, 18)
                .addComponent(jLabelPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWorkPhone)
                    .addComponent(jTextFieldWorkPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHomePhone)
                    .addComponent(jTextFieldHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCelular1)
                    .addComponent(jTextFieldCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCelular2)
                    .addComponent(jTextFieldCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelEmails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMain)
                    .addComponent(jTextFieldMainEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddSecondary)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonSelectSecondary))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectedSecondary)
                    .addComponent(jTextFieldSelectedSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmSecondary))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboBoxSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSecondaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSecondaryActionPerformed

    private void jTextFieldWorkPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWorkPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWorkPhoneActionPerformed

    private void jTextFieldHomePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHomePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHomePhoneActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        Iterable<CountryCode> it = this.ctrl.persistenceContext().repositories().countryCodes().findAll();
        Set<CountryCode> ccList = new HashSet<>();
        for (CountryCode countCode : it) {
            ccList.add(countCode);
        }
        this.cepe.updatePhones(jTextFieldWorkPhone.getText(), jTextFieldHomePhone.getText(), jTextFieldCelular1.getText(),
                jTextFieldCelular2.getText(), ccList);
        this.cepe.updateMainEmail(jTextFieldMainEmail.getText());

        try {
            this.ctrl.updateContact(this.cepe, cepe.name(), cepe.firstName(), cepe.lastName());
        } catch (DataConcurrencyException | DataIntegrityViolationException ex) {
            JOptionPane.showMessageDialog(this, "The contact wasn't successfully saved!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonAddSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSecondaryActionPerformed
        boolean ret = this.cepe.addSecondaryEmail(jTextFieldAddSecondary.getText());
        if (ret == false) {
            JOptionPane.showMessageDialog(null, "Invalid secondary email", "Error", JOptionPane.ERROR_MESSAGE);
        }
        jComboBoxSecondary.setModel(lapr4.blue.s1.core.n1150595.emailAndPhoneEdition.Utils.
                comboBoxModelEmails(this.cepe.secondaryEmails()));
    }//GEN-LAST:event_jButtonAddSecondaryActionPerformed

    private void jButtonSelectSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectSecondaryActionPerformed
        jTextFieldSelectedSecondary.setText(jComboBoxSecondary.getSelectedItem().toString());
    }//GEN-LAST:event_jButtonSelectSecondaryActionPerformed

    private void jTextFieldSelectedSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSelectedSecondaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSelectedSecondaryActionPerformed

    private void jButtonConfirmSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmSecondaryActionPerformed
        this.cepe.updateSecondaryEmail((Email) jComboBoxSecondary.getSelectedItem(), jTextFieldSelectedSecondary.getText());
        jComboBoxSecondary.setModel(lapr4.blue.s1.core.n1150595.emailAndPhoneEdition.Utils.
                comboBoxModelEmails(this.cepe.secondaryEmails()));
    }//GEN-LAST:event_jButtonConfirmSecondaryActionPerformed

    private void jTextFieldAddSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddSecondaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddSecondaryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSecondary;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConfirmSecondary;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonSelectSecondary;
    private javax.swing.JComboBox<String> jComboBoxSecondary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCelular1;
    private javax.swing.JLabel jLabelCelular2;
    private javax.swing.JLabel jLabelEmails;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelHomePhone;
    private javax.swing.JLabel jLabelMain;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelSelectedSecondary;
    private javax.swing.JLabel jLabelWorkPhone;
    private javax.swing.JTextField jTextFieldAddSecondary;
    private javax.swing.JTextField jTextFieldCelular1;
    private javax.swing.JTextField jTextFieldCelular2;
    private javax.swing.JTextField jTextFieldHomePhone;
    private javax.swing.JTextField jTextFieldMainEmail;
    private javax.swing.JTextField jTextFieldSelectedSecondary;
    private javax.swing.JTextField jTextFieldWorkPhone;
    // End of variables declaration//GEN-END:variables
}
