@startuml sdUC01.1Core.png
actor User
participant EnableDisableExtensionUI as ui
participant EnableDisableExtensionController as ctrl
participant UIController as uic
participant UIExtension as uie
participant ExtensionManager as em
participant Extension as e


User->ui: The user selects the option of enabling and disabling extension
ui->ctrl: create(ctrl);
ui->ctrl: getExtensions();
ctrl->em: getInstance();
ctrl->em: getExtensions();
ui-->User: The System shows a list of the various extensions avaliable
User->ui: The user selects an extension
ui->ctrl: setUIExtension(extName);
ctrl->em: getInstance();
ctrl->em: getExtension(extName);
ui-->User: The System asks if the user wants to enable/disable the extension
User->ui: The user accepts
ui->ctrl: changeExtensionState(option);
loop
ctrl->uic: getExtensions()[i];
uic->uie: getExtension().equals(extension);
end
alt
ctrl->uic: getExtensions()[num];
uic->uie: getCellDecorator();
ctrl->uie: enabled : getEnabledProperty("celldecorator");
ctrl->uie: getCellDecorator().setEnabled(option);
ctrl->uie: setEnabledProperty("celldecorator", option);
end
alt
ctrl->uic: getExtensions()[num];
uic->uie: getTableDecorator();
ctrl->uie: enabled : getEnabledProperty("tabledecorator");
ctrl->uie: getTableDecorator().setEnabled(option);
ctrl->uie: setEnabledProperty("tabledecorator", option);
end
alt
ctrl->uic: getExtensions()[num];
uic->uie: getToolBar();
ctrl->uie: enabled : getEnabledProperty("toolbar");
ctrl->uie: toolbar : getToolBar();
loop
ctrl->uie: toolbar.getComponents()[j].setEnabled(option);
ctrl->uie: toolbar.getComponents()[j].setVisible(option);
end
ctrl->uie: setEnabledProperty("toolbar", option);
end
alt
ctrl->uic: getExtensions()[num];
uic->uie: getSideBar();
ctrl->uie: enabled : getEnabledProperty("sidebar");
ctrl->uie: sidebar : getSideBar();
loop
ctrl->uie: sidebar.getComponents()[j].setEnabled(option);
ctrl->uie: sidebar.getComponents()[j].setVisible(option);
end
ctrl->uie: setEnabledProperty("sidebar", option);
end
alt
ctrl->uic: getExtensions()[num];
uic->uie: getMenu();
ctrl->uie: getMenu().setEnabled(option);
ctrl->uie: getMenu().setVisible(option);
end
ui-->User: The System shows a confirmation message

@enduml