  @startuml IPC01.1_UDP_sender_update.png
    skinparam handwritten false
    skinparam monochrome false
    skinparam packageStyle rect
    skinparam defaultFontName FG Virgil
    skinparam shadowing false

  box "Share Cell Extension Sender UDP"
    participant "ShareCellExtension"
    participant "ShareCellController"
    participant "ExtensionConnectionManager"
    participant "ConnectionUDP"
    participant "UDPStringSenderManager"
  end box

create ShareCellController 
    ShareCellExtension -> ShareCellController : new()
note right of ShareCellExtension : automatic execution\n without user intervening
create ExtensionConnectionManager 
    ShareCellController -> ExtensionConnectionManager : new()
    ExtensionConnectionManager -> ExtensionConnectionManager : sendUdpAnnoucementsTimmed(seconds)
create ConnectionUDP 
    ExtensionConnectionManager -> ConnectionUDP : new(udpPort)
opt timedCicle
    ExtensionConnectionManager -> ConnectionUDP : serverSendMessage(message, addressToSend)
create UDPStringSenderManager
    ConnectionUDP -> UDPStringSenderManager : new(message, addressToSend)
    ConnectionUDP -> UDPStringSenderManager : send()

    UDPStringSenderManager -> UDPStringSenderManager : send()
end   
@enduml


