/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr4.red.s2.lang.n1150825.IntermediateWizard.ui;

import csheets.core.formula.Function;
import csheets.core.formula.FunctionParameter;
import csheets.core.formula.compiler.FormulaCompilationException;
import csheets.ui.ctrl.UIController;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lapr4.red.s2.lang.n1150825.IntermediateWizard.controller.IntermediateWizardController;

/**
 *
 * @author Miguel Morgado 1150605
 */
public class IntermediateWizardUI extends javax.swing.JFrame {

    private UIController uiC;
    private IntermediateWizardController controller;
    Function[] functions;
    //keeps the number of parameters from the selected function
    //and it's also used to know if all the parameters have been inputted
    private int parameters=0;
    //these three variables bellow are responsible for keeping notion if a parameter
    //has been passed through the parameter boxes
    private int parameter1=0;
    private int parameter2=0;
    private int parameter3=0;

    /**
     * Creates new form FunctionBasicWizardUI
     * @param uiC
     */
    public IntermediateWizardUI(UIController uiC) {
        initComponents();

        this.uiC = uiC;
        this.controller = new IntermediateWizardController();
        setLocationRelativeTo(null);
        setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        updateComboBox();
    }

    void updateComboBox() {
        functions = controller.functions();

        for (Function f : functions) {
            jComboBox1.addItem(controller.getFunctionIdentifier(f));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Intermidiate Wizard");

        jLabel2.setText("Function:");

        jComboBox1.setAutoscrolls(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Syntax:");

        jLabel4.setText("Description:");

        jButton3.setText("Select");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("Parametro1");
        jLabel5.setVisible(false);
        jLabel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel5PropertyChange(evt);
            }
        });

        jTextField2.setText("Parametro1");
        jTextField2.setVisible(false);
        jTextField2.setEditable(false);
        lapr4.red.s2.lang.n1150825.IntermediateWizard.ui.IntermediateWizardListener action1 = new lapr4.red.s2.lang.n1150825.IntermediateWizard.ui.IntermediateWizardListener(){
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode()==KeyEvent.VK_ENTER && (jTextField2.getText()!="" || jTextField2.getText()!="\n" )){
                    String temp=jTextField1.getText().substring(0, jTextField1.getText().indexOf("(")+1);
                    temp+=jTextField2.getText();
                    if(jTextField1.getText().indexOf(",")!=-1){
                        temp+=jTextField1.getText().substring(jTextField1.getText().indexOf(","));
                    }else{
                        temp+=")";
                    }
                    jTextField1.setText(temp);
                    if(parameter1!=0){
                        parameter1=0;
                        parameters-=1;
                        if(parameters!=0) jLabel8.setText("There are "+parameters+" parameters missing");
                    }
                    if(parameters==0){
                        try {
                            jLabel8.setText(""+controller.cellPreview(jTextField1.getText()));
                        } catch (FormulaCompilationException ex) {
                            jLabel8.setText("INVALID PARAMETER");
                            Logger.getLogger(IntermediateWizardUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        };
        jTextField2.addKeyListener(action1);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Parametro2");
        jLabel6.setVisible(false);

        jTextField3.setText("Parametro2");
        jTextField3.setVisible(false);
        jTextField3.setEditable(false);
        lapr4.red.s2.lang.n1150825.IntermediateWizard.ui.IntermediateWizardListener action2 = new lapr4.red.s2.lang.n1150825.IntermediateWizard.ui.IntermediateWizardListener(){
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode()==KeyEvent.VK_ENTER && (jTextField3.getText()!="" || jTextField3.getText()!="\n" )){
                    String temp=jTextField1.getText().substring(0, jTextField1.getText().indexOf(",")+1);
                    temp+=jTextField3.getText();
                    if(jTextField1.getText().lastIndexOf(",")!=jTextField1.getText().indexOf(",")){
                        temp+=jTextField1.getText().substring(jTextField1.getText().lastIndexOf(","));
                    }else{
                        temp+=")";
                    }
                    jTextField1.setText(temp);
                    if(parameter2!=0){
                        parameter2=0;
                        parameters-=1;
                        if(parameters!=0) jLabel8.setText("There are "+parameters+" parameters missing");
                    }
                    if(parameters==0){
                        try {
                            jLabel8.setText(""+controller.cellPreview(jTextField1.getText()));
                        } catch (FormulaCompilationException ex) {
                            jLabel8.setText("INVALID PARAMETER");
                            Logger.getLogger(IntermediateWizardUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        };
        jTextField3.addKeyListener(action2);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Parametro3");
        jLabel7.setVisible(false);

        jTextField4.setText("Parametro3");
        jTextField4.setVisible(false);
        jTextField4.setEditable(false);
        lapr4.red.s2.lang.n1150825.IntermediateWizard.ui.IntermediateWizardListener action3 = new lapr4.red.s2.lang.n1150825.IntermediateWizard.ui.IntermediateWizardListener(){
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode()==KeyEvent.VK_ENTER && (jTextField4.getText()!="" || jTextField4.getText()!="\n" )){
                    String temp=jTextField1.getText().substring(0, jTextField1.getText().lastIndexOf(",")+1);
                    temp+=jTextField4.getText();
                    temp+=")";
                    jTextField1.setText(temp);
                    if(parameter3!=0){
                        parameter3=0;
                        parameters-=1;
                        if(parameters!=0) jLabel8.setText("There are "+parameters+" parameters missing");
                    }
                    if(parameters==0){
                        try {
                            jLabel8.setText(""+controller.cellPreview(jTextField1.getText()));
                        } catch (FormulaCompilationException ex) {
                            jLabel8.setText("INVALID PARAMETER");
                            Logger.getLogger(IntermediateWizardUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        };
        jTextField4.addKeyListener(action3);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            controller.setFormulaBarExpression(uiC, jTextField1.getText());
        } catch (FormulaCompilationException ex) {
            JOptionPane.showMessageDialog(this, "INVALID PARAMETERS!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        parameter1=0;
        parameter2=0;
        parameter3=0;
        jLabel8.setVisible(false);
        jLabel5.setVisible(false);
        jTextField2.setEditable(false);
        jTextField2.setVisible(false);
        jLabel6.setVisible(false);
        jTextField3.setEditable(false);
        jTextField3.setVisible(false);
        jLabel7.setVisible(false);
        jTextField4.setEditable(false);
        jTextField4.setVisible(false);
        int index = jComboBox1.getSelectedIndex();
        FunctionParameter[] fp = controller.functionParameters(functions[index]);

        ArrayList<String> names = new ArrayList<>();
        ArrayList<String> opt = new ArrayList<>();
        ArrayList<String> descs = new ArrayList<>();

        for (FunctionParameter p : fp) {
            names.add(controller.parameterName(p));
            descs.add(controller.parameterDescription(p));
            boolean b = controller.parameterOptional(p);

            if (b == true) {
                opt.add("Optional");
            } else {
                opt.add("Required");
            }
        }

        // syntax
        String str = ("= " + controller.getFunctionIdentifier(functions[index]) + "(");
        //keeps the number of parameters from the function
        parameters=names.size();
        for (int i = 0; i < parameters; i++) {
            if (i == parameters - 1) {
                str += names.get(i);
                //makes one of the parameter boxes active
                jLabel5.setVisible(true);
                jTextField2.setEditable(true);
                jTextField2.setVisible(true);
                //used to know if a parameter was already given through this edit box
                parameter1=1;
            } else {
                str += (names.get(i) + ", ");
                if(i==0){
                    //In the case of 2 parameters it shows the 2º parameter box
                    jLabel6.setVisible(true);
                    jTextField3.setEditable(true);
                    jTextField3.setVisible(true);
                    //used to know if a parameter was already given through this edit box
                    parameter2=1;
                }else{
                    //In the case of 3 parameters it shows the 3º parameter box
                    jLabel7.setVisible(true);
                    jTextField4.setEditable(true);
                    jTextField4.setVisible(true);
                    //used to know if a parameter was already given through this edit box
                    parameter3=1;
                }
            }
        }
        str += ")";
        
        //sets the syntax of the function
        jTextField1.setText(str);
        jTextField1.setEditable(false);

        str = functions[index].getDescription() + "\n\n";
        for (int i = 0; i < parameters; i++) {
            str += names.get(i) + ": ";
            str += descs.get(i) + " (";
            str += opt.get(i) + ").\n";
        }
        //sets the description of the function
        jTextArea1.setText(str);
        //sees if there are parameters to be incerted or if it should call the cellPreview
        if(parameters!=0){
            jLabel8.setText("There are "+parameters+" parameters missing");
        }else{
            try {
                jLabel8.setText(""+controller.cellPreview(jTextField1.getText()));
            } catch (FormulaCompilationException ex) {
                Logger.getLogger(IntermediateWizardUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jLabel8.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jLabel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5PropertyChange

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
