/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr4.blue.s1.core.n1150433.addressEdition.ui;

import csheets.ui.ctrl.UIController;
import eapli.framework.persistence.DataConcurrencyException;
import eapli.framework.persistence.DataIntegrityViolationException;
import java.io.FileNotFoundException;
import java.io.IOException;
import lapr4.blue.s1.core.n1150433.addressEdition.application.AddressEditionController;
import lapr4.white.s1.core.n4567890.contacts.domain.Contact;

/**
 *
 * @author Débora Costa - 1150433
 */
public class AddressEditionUI extends javax.swing.JFrame {
    AddressEditionController controller;
    Contact contact;
    /**
     * Creates new form AddressEditionUI
     */
    public AddressEditionUI(UIController uiController, Contact contact) throws IOException, FileNotFoundException, DataConcurrencyException, DataIntegrityViolationException {
        initComponents();
        controller = new AddressEditionController(uiController.getUserProperties());
        this.contact = contact;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mainStreet = new javax.swing.JTextField();
        mainTown = new javax.swing.JTextField();
        mainPostalCode = new javax.swing.JTextField();
        mainCity = new javax.swing.JTextField();
        mainCountry = new javax.swing.JTextField();
        confirmAddressButton = new javax.swing.JButton();
        cancelAddressButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        secondaryCity = new javax.swing.JTextField();
        secondaryCountry = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        secondaryStreet = new javax.swing.JTextField();
        secondaryTown = new javax.swing.JTextField();
        secondaryPostalCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Address");

        jLabel2.setText("Street:");

        jLabel3.setText("Town:");

        jLabel4.setText("Postal Code:");

        jLabel5.setText("City:");

        jLabel6.setText("Country:");

        String s="";
        if(this.contact!=null){
            if(this.contact.mainAddress().street()!=null){
                s=this.contact.mainAddress().street();
            }
        }
        mainStreet.setText(s);

        s="";
        if(this.contact!=null){
            if(this.contact.mainAddress().town()!=null){
                s=this.contact.mainAddress().town();
            }
        }
        mainTown.setText(s);

        s="";
        if(this.contact!=null){
            if(this.contact.mainAddress().postalCode().postalCode() !=null){
                s=this.contact.mainAddress().postalCode().postalCode();
            }
        }
        mainPostalCode.setText(s);

        s="";
        if(this.contact!=null){
            if(this.contact.mainAddress().city()!=null){
                s=this.contact.mainAddress().city();
            }
        }
        mainCity.setText(s);

        s="";
        if(this.contact!=null){
            if(this.contact.mainAddress().country()!=null){
                s=this.contact.mainAddress().country();
            }
        }
        mainCountry.setText(s);

        confirmAddressButton.setText("Confirm");
        confirmAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddressButtonActionPerformed(evt);
            }
        });

        cancelAddressButton.setText("Cancel");
        cancelAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddressButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Main:");

        jLabel8.setText("Secondary:");

        s="";
        if(this.contact!=null){
            if(this.contact.secondaryAddress().city()!=null){
                s=this.contact.secondaryAddress().city();
            }
        }
        secondaryCity.setText(s);

        s="";
        if(this.contact!=null){
            if(this.contact.secondaryAddress().country()!=null){
                s=this.contact.secondaryAddress().country();
            }
        }
        secondaryCountry.setText(s);

        jLabel9.setText("Street:");

        jLabel10.setText("Town:");

        jLabel11.setText("Postal Code:");

        jLabel12.setText("City:");

        jLabel13.setText("Country:");

        s="";
        if(this.contact!=null){
            if(this.contact.secondaryAddress().street()!=null){
                s=this.contact.secondaryAddress().street();
            }
        }
        secondaryStreet.setText(s);

        s="";
        if(this.contact!=null){
            if(this.contact.secondaryAddress().town()!=null){
                s=this.contact.secondaryAddress().town();
            }
        }
        secondaryTown.setText(s);

        s="";
        if(this.contact!=null){
            if(this.contact.secondaryAddress().postalCode().postalCode()!=null){
                s=this.contact.secondaryAddress().postalCode().postalCode();
            }
        }
        secondaryPostalCode.setText(s);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(299, 299, 299))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(mainTown))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(mainStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(mainPostalCode))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(mainCity))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(mainCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(secondaryTown))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(secondaryStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(secondaryPostalCode))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(secondaryCity))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(secondaryCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmAddressButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelAddressButton)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(mainStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mainTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(mainPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(mainCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(mainCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(secondaryStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(secondaryTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(secondaryPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(secondaryCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(secondaryCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmAddressButton)
                    .addComponent(cancelAddressButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddressButtonActionPerformed
        controller.setMainAddress(controller.createAddress(mainStreet.getText(), 
               mainTown.getText(), mainPostalCode.getText(), mainCity.getText(), mainCountry.getText()));
        controller.setSecondaryAddress(controller.createAddress(secondaryStreet.getText(), secondaryTown.getText(), 
               secondaryPostalCode.getText(), secondaryCity.getText(), secondaryCountry.getText()));
        this.dispose();
    }//GEN-LAST:event_confirmAddressButtonActionPerformed

    private void cancelAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddressButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelAddressButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelAddressButton;
    private javax.swing.JButton confirmAddressButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mainCity;
    private javax.swing.JTextField mainCountry;
    private javax.swing.JTextField mainPostalCode;
    private javax.swing.JTextField mainStreet;
    private javax.swing.JTextField mainTown;
    private javax.swing.JTextField secondaryCity;
    private javax.swing.JTextField secondaryCountry;
    private javax.swing.JTextField secondaryPostalCode;
    private javax.swing.JTextField secondaryStreet;
    private javax.swing.JTextField secondaryTown;
    // End of variables declaration//GEN-END:variables
}
