/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr4.green.s3.ipc.n1150759.chatApplication.ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import javax.swing.JOptionPane;
import lapr4.red.s1.ipc.n1151117.chatApplication.ExtensionConnectionManagerChatApplication;
import lapr4.red.s1.ipc.n1151117.chatApplication.application.ChatApplicationController;
import lapr4.red.s1.ipc.n1151117.chatApplication.application.SendMessageController;
import lapr4.red.s1.ipc.n1151117.chatApplication.domain.Chat;
import lapr4.red.s1.ipc.n1151117.chatApplication.domain.Message;
import lapr4.red.s1.ipc.network.library.NetworkAddress;
import lapr4.red.s1.ipc.network.library.Utils;
import lapr4.green.s3.ipc.n1150759.chatApplication.IObserverChatRoom;

/**
 *
 * @author Jorge Campos <1150759@isep.ipp.pt>
 */
public class ChatRoomUI extends javax.swing.JFrame implements IObserverChatRoom {
    
    private final Chat chat;
    
    private final ChatApplicationController chatCtrl;
    
    private final SendMessageController sendMsgCtrl;

    /**
     * Creates new form ChatRoomUI
     * 
     * @param chat Chat room
     * @param chatCtrl Chat application controller
     */
    public ChatRoomUI(Chat chat, ChatApplicationController chatCtrl) {
        this.chat = chat;
        this.chatCtrl = chatCtrl;
        this.sendMsgCtrl = new SendMessageController(chatCtrl.extensionConnectionManager());
        this.chatCtrl.extensionConnectionManager().registNewChatRoomObserver(this);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOwner = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaMsg = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Room's name:");

        txtName.setEditable(false);
        txtName.setText(this.chat.getRoomName());

        jLabel2.setText("Owner:");

        txtOwner.setEditable(false);
        txtOwner.setText(this.chatCtrl.extensionConnectionManager().findProfileNickByIP(this.chat.getOwner().getAddress())
        );

        areaChat.setColumns(20);
        areaChat.setRows(5);
        jScrollPane1.setViewportView(areaChat);

        jLabel3.setText("Message");

        areaMsg.setColumns(20);
        areaMsg.setRows(5);
        jScrollPane2.setViewportView(areaMsg);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnLeave.setText("Leave Room");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLeave, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 420, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose)
                            .addComponent(btnSend))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(txtOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeave)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        Set<NetworkAddress> receivers = this.chat.allOtherUsersInChat();
        
        // Creates the message
        if (areaMsg.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Message can't be empty!", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        Message message = this.sendMsgCtrl.createMessage(areaMsg.getText(), 
                Utils.ownIpAddress(), receivers);
        // Defines the message
        this.sendMsgCtrl.addMessageToSend(message);
        // Sends the message to all receivers
        if (this.sendMsgCtrl.sendMessageToChatRoom())
            this.areaMsg.setText(null);
        
        this.areaMsg.requestFocus();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        if (this.chat.leaveChatRoom(Utils.ownIpAddress())) {
            JOptionPane.showMessageDialog(null, "You left the chat room.");
            if (this.chat.allUsersInChat().isEmpty()) {
                this.chatCtrl.deleteChatRoom(this.chat);
                JOptionPane.showMessageDialog(null, "The chat room was deleted.");
            }
            dispose();
        } else
            JOptionPane.showMessageDialog(null, "Couldn't leave the chat room.");
    }//GEN-LAST:event_btnLeaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaChat;
    private javax.swing.JTextArea areaMsg;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOwner;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateChat(Message message) {
        String timeStamp = new SimpleDateFormat("HH:mm").format(new Date());
        this.areaChat.append(timeStamp + " - " + 
                chatCtrl.extensionConnectionManager().
                        findProfileNickByIP(message.messageSender().
                                getAddress()) + ": " + message.message() + "\n");
        
        /**
         * Auto scrolls the chat area to the bottom
         */
        this.areaChat.setCaretPosition(this.areaChat.getDocument().getLength());
    }
}
