/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr4.green.s3.ipc.n1150759.chatApplication.ui;

import java.util.ArrayList;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lapr4.green.s3.ipc.n1150759.chatApplication.IObservableChatRoomList;
import lapr4.green.s3.ipc.n1150759.chatApplication.IObserverChatRoomList;
import lapr4.red.s1.ipc.n1151117.chatApplication.application.ChatApplicationController;
import lapr4.red.s1.ipc.n1151117.chatApplication.domain.Chat;
import lapr4.red.s1.ipc.network.library.NetworkAddress;
import lapr4.red.s1.ipc.network.library.NetworkMachinesList;

/**
 *
 * @author Jorge Campos <1150759@isep.ipp.pt>
 */
public class CreateChatRoomUI extends javax.swing.JDialog implements 
        IObservableChatRoomList {

    private final ChatApplicationController chatCtrl;
    
    private Chat created;
    
    private final ArrayList observers;

    /**
     * Creates new form CreateChatRoomUI
     * @param chatCtrl
     */
    public CreateChatRoomUI(ChatApplicationController chatCtrl) {
        super(new JFrame(), true);
        this.chatCtrl = chatCtrl;
        this.observers = new ArrayList<>();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPublic = new javax.swing.JRadioButton();
        btnPrivate = new javax.swing.JRadioButton();
        btnCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Create Chat Room");

        jLabel2.setText("Room name:");

        jLabel3.setText("Type:");

        buttonGroup1.add(btnPublic);
        btnPublic.setSelected(true);
        btnPublic.setText("Public");

        buttonGroup1.add(btnPrivate);
        btnPrivate.setText("Private");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnPublic)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrivate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnCreate)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrivate)
                        .addComponent(btnPublic)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String name = null;
        String type;
        boolean canCreate = false;
        
        if (txtName.getText().trim().isEmpty())
            JOptionPane.showMessageDialog(null, "Name can't be empty!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        else {
            name = txtName.getText();
            canCreate = true;
        }
        
        if (btnPublic.isSelected())
            type = "public";
        else
            type = "private";
        
        if (canCreate) {
            created = this.chatCtrl.createChat(name, type);

            int tcpPort;
            NetworkMachinesList machines = this.chatCtrl.extensionConnectionManager().returnMapMembers();
            Set<NetworkAddress> onlineUsers = this.chatCtrl.
                    extensionConnectionManager().returnMapMembers().findAllAdresses();
            
            for (NetworkAddress address : onlineUsers) {
                NetworkAddress netAd = machines.findNetworkAddressByIP(address.getAddress());
                tcpPort = machines.findTCPPortByAddress(netAd);
                this.chatCtrl.extensionConnectionManager().sendTcp(created, tcpPort, address);
            }
            
            notifyObserversChatRoomList();
        }
        
        dispose();
    }//GEN-LAST:event_btnCreateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JRadioButton btnPrivate;
    private javax.swing.JRadioButton btnPublic;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void registNewChatRoomListObserver(IObserverChatRoomList o) {
        this.observers.add(o);
    }
    
    @Override
    public void notifyObserversChatRoomList() {
        for (int i = 0; i < observers.size(); i++) {
            IObserverChatRoomList obs = (IObserverChatRoomList) observers.get(i);
            obs.updateChatRoomList(created);
        }
    }
}
