@startuml ipc_07_1_design_1.png
  participant "uic : UIController" as UIC
  participant ExtensionManager as ExtM
  participant "extension : ExtensionWorkbookSearch" as EExample
  participant "uiExtension : UIWorkbookSearchExtension" as UIExt
  participant "WorkbookSearchUI : JPanel" as ws
  UIC -> ExtM : extensions=getExtensions();
  loop for Extension ext : extensions
  	UIC -> EExample : uiExtension=getUIExtension(this);
  	activate EExample
  	create UIExt
  	EExample -> UIExt : new(extension, uic)
  	deactivate EExample
  	UIExt -> UIExt : getSideBar();
  	activate UIExt
  	create ws
  	UIExt -> ws :  new (uic)  	
  	deactivate UIExt
  	UIC -> UIC : uiExtensions.add(uiExtension);
  end
@enduml